#!/usr/bin/env python3
"""tm_src/chardesc_*.tsv (idx<TAB>human_en<TAB>zombie_en) -> tm/characters_desc.tsv (jp<TAB>en).
Blank or '-' columns are skipped. Keys are the JP text of that record, so records that
share a description get the same English."""
import json, os, glob
HERE = os.path.dirname(os.path.abspath(__file__))
base = json.load(open(os.path.join(HERE, 'work', 'base_json', 'characterData.bin.mid.json'), encoding='utf-8'))
out, n = {}, 0
for f in sorted(glob.glob(os.path.join(HERE, 'tm_src', 'chardesc_*.tsv'))):
    for line in open(f, encoding='utf-8'):
        line = line.rstrip('\n')
        if not line or line.startswith('#'):
            continue
        parts = (line.split('\t') + ['', ''])[:3]
        i = int(parts[0])
        for field, en in (('HumanDescription', parts[1]), ('ZombieDescription', parts[2])):
            en = en.strip()
            if en and en != '-' and base[i][field]:
                out.setdefault(base[i][field], en)
                out[f'{i}:{field}'] = en        # per-record key wins over shared JP text
                n += 1
with open(os.path.join(HERE, 'tm', 'characters_desc.tsv'), 'w', encoding='utf-8') as f:
    f.write('# generated by chardesc_to_tm.py - edit tm_src/chardesc_*.tsv instead\n')
    for k, v in out.items():
        f.write(f'{k}\t{v}\n')
print(f'{n} description entries -> {len(out)} unique JP keys')
